# Generated by Django 4.2 on 2023-04-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_grow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
