# Generated by Django 4.2 on 2023-04-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_grow', '0002_device_device_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_threshold', models.FloatField()),
                ('humidity_threshold', models.FloatField()),
            ],
        ),
    ]
