# Generated by Django 4.2 on 2023-05-01 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_grow', '0003_climatecontrolsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatecontrolsettings',
            name='device_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heaters', to='smart_grow.device'),
        ),
        migrations.AddField(
            model_name='climatecontrolsettings',
            name='device_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='humidifiers', to='smart_grow.device'),
        ),
    ]
