# Generated by Django 4.2 on 2023-05-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_grow', '0004_climatecontrolsettings_device_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatecontrolsettings',
            name='device_1',
            field=models.CharField(default='zro', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='climatecontrolsettings',
            name='device_2',
            field=models.CharField(default='zro', max_length=100),
            preserve_default=False,
        ),
    ]
