# Generated by Django 4.2 on 2023-05-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_grow', '0007_alter_sensordata_device_name_alter_sensordata_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='device_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
